name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

#Each job is run on a new server
jobs:
        
  docker-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build and push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: 7wesley/cards-backend
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
